gui:
  expandFocusedSidePanel: true
  theme:
    selectedLineBgColor:
      - black
  showBottomLine: false
git:
  diffRenderers:
    - colorArg: always
      command: "delta --dark --paging=never"
services:
  "rensa-family.ghe.com": "github:rensa-family.ghe.com"
notARepository: quit
