# tuxedo config
theme = Catppuccin Mocha
density = comfortable
sort = priority
show_left = true
show_right = true
show_line_num = true
show_status_bar = true
show_done = true
show_future = false

# Keys of key:value pairs to hide in the UI
# hide_keys = uid, sync
